/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  darkMode: "class",
  theme: {
    extend: {
      "colors": {
          "on-secondary": "#3c0091",
          "on-primary-fixed-variant": "#005233",
          "inverse-on-surface": "#2d3135",
          "on-tertiary-fixed-variant": "#900037",
          "bear-glow": "#9F1239",
          "background": "#101418",
          "secondary-fixed-dim": "#d0bcff",
          "secondary-fixed": "#e9ddff",
          "bull-glow": "#059669",
          "surface-container-low": "#191c20",
          "inverse-primary": "#006c46",
          "primary-fixed-dim": "#00e296",
          "on-secondary-fixed": "#23005c",
          "void-obsidian": "#030508",
          "secondary": "#d0bcff",
          "on-secondary-container": "#c4abff",
          "inverse-surface": "#e0e2e8",
          "on-tertiary-fixed": "#400014",
          "surface": "#101418",
          "outline": "#849589",
          "primary-container": "#00f2a1",
          "on-tertiary": "#670024",
          "error": "#ffb4ab",
          "on-primary-container": "#006943",
          "primary-fixed": "#4dffb1",
          "tertiary": "#ffecee",
          "on-surface": "#e0e2e8",
          "on-background": "#e0e2e8",
          "mesh-teal": "#06B6D4",
          "on-primary-fixed": "#002112",
          "error-container": "#93000a",
          "surface-container-highest": "#32353a",
          "tertiary-fixed-dim": "#ffb2bd",
          "tertiary-fixed": "#ffd9dd",
          "surface-tint": "#00e296",
          "mesh-orchid": "#D946EF",
          "on-secondary-fixed-variant": "#5516be",
          "surface-container-high": "#272a2f",
          "specular-glow": "rgba(255, 255, 255, 0.08)",
          "secondary-container": "#571bc1",
          "tertiary-container": "#ffc6cd",
          "surface-variant": "#32353a",
          "surface-bright": "#36393e",
          "surface-container": "#1d2024",
          "abyssal-slate": "#0A0E17",
          "on-primary": "#003822",
          "outline-variant": "#3b4a40",
          "glass-plate-bg": "rgba(13, 20, 35, 0.45)",
          "on-error-container": "#ffdad6",
          "surface-container-lowest": "#0b0e13",
          "on-tertiary-container": "#b70047",
          "surface-dim": "#101418",
          "on-error": "#690005",
          "primary": "#c0ffd9",
          "mesh-cobalt": "#4F46E5",
          "on-surface-variant": "#b9cbbe"
      },
      "borderRadius": {
          "DEFAULT": "0.25rem",
          "lg": "0.5rem",
          "xl": "0.75rem",
          "full": "9999px"
      },
      "spacing": {
          "unit": "4px",
          "gutter": "1.5rem",
          "grid-margin": "2rem"
      },
      "fontFamily": {
          "display-lg": ["Sora", "sans-serif"],
          "headline-md": ["Sora", "sans-serif"],
          "data-mono": ["JetBrains Mono", "monospace"],
          "metadata-tiny": ["JetBrains Mono", "monospace"],
          "body-base": ["Hanken Grotesk", "sans-serif"]
      }
    }
  },
  plugins: [],
}
